{% set version = "1.0.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gghoriplot
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggHoriPlot_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggHoriPlot/ggHoriPlot_{{ version }}.tar.gz
  sha256: 67199e0a94bf2793e4bd4ee51127dcfab16bba7f8ec24f7ed2932b9cf13165e9

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr
    - r-ggplot2
    - r-glue
    - r-magrittr
    - r-stringr
    - r-tidyr
  run:
    - r-base
    - r-dplyr
    - r-ggplot2
    - r-glue
    - r-magrittr
    - r-stringr
    - r-tidyr

test:
  commands:
    - $R -e "library('ggHoriPlot')"           # [not win]
    - "\"%R%\" -e \"library('ggHoriPlot')\""  # [win]

about:
  home: https://rivasiker.github.io/ggHoriPlot/, https://github.com/rivasiker/ggHoriPlot
  license: GPL-3.0-only
  summary: A user-friendly, highly customizable R package for building horizon plots in the 'ggplot2' environment.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
